### PR TITLE
player reputation is case insensitive

### LINKED ISSUE #710: Whitelist doesn't work
My creeps will attack enemy creeps, friends within the whitelist, and even my own creeps.
This only happened after of the task.repuatition.

See this:
http://screeps.com/s/cRmmJx

### PR DESCRIPTION
**Pull request by karlthepagan**
I think this is the last must fix for 2017-2

this resolves #710

### CODE REVIEW

**Comment by karlthepagan** [comment]
I do need to test this

File: task.reputation.js [hunk 1]
```diff
@@ -26,15 +26,18 @@ const mod = {
         const reps = mod.cache('score');
         if( username === undefined ) {
             return reps;
-        } else if( reps[username] ) {
-            return reps[username];
+        }
+        const name = username && username.toLowerCase();
```
Comment (chobobobo) [inline task.reputation.js]: You could move this up to line 27, but it still functions the way it is.
