### PR TITLE
Transaction Visuals Fix

### LINKED ISSUE #845: Undef TypeError in Visuals
after sending some res to another player with:
`Game.rooms.E18N73.terminal.send(RESOURCE_UTRIUM, 1000, 'E15N73', 'AKK!');
 Game.rooms.E18N72.terminal.send(RESOURCE_OXYGEN, 1000, 'E15N73', 'AKK!');
 Game.rooms.E17N71.terminal.send(RESOURCE_OXYGEN, 1000, 'E15N73', 'AKK!');`

i got this

TypeError: Cannot read property 'price' of undefined
    at transactions.forEach.transaction (visuals:331:66)
    at Array.forEach (native)
    at Function.drawTransactions (visuals:322:17)
    at Function.run (visuals:60:13)
    at Object.module.exports.loop (main:288:76)
    at __mainLoop:1:52

### PR DESCRIPTION
**Pull request by Spedwards**
Should resolve #845 and another unreported case (I can't remember)

### CODE REVIEW

File: visuals.js [hunk 1]
```diff
@@ -381,11 +381,13 @@ module.exports = class Visuals {
             transactions.forEach(transaction => {
                 const outgoing = transaction.sender.username === room.controller.owner.username;
                 const toSelf = transaction.recipient ? transaction.sender.username === transaction.recipient.username : false;
-                const colour = outgoing ? '#00FF00' : '#FF0000';
+                const receiving = room.name === transaction.to;
+                const colour = outgoing || receiving ? '#00FF00' : '#FF0000';
```
Comment (Spedwards) [inline visuals.js]: `outgoing || receiving` may need to be reversed. May also need a separate check.

File: visuals.js [hunk 2]
```diff
@@ -381,11 +381,13 @@ module.exports = class Visuals {
...
                 const prefix = outgoing ? '+' : '-';
                 let text = '';
-                if ( toSelf ) {
-                    text = `${transaction.to} : ${transaction.amount} ${transaction.resourceType}`;
+                if (toSelf || !transaction.order) {
```
Comment (Spedwards) [inline visuals.js]: An order may not exist (#845), in which case, default to an inter-room format.

**Comment by Spedwards** [comment]
Needs some testing. There are a few cases and I need to make sure they're right:

 - Selling resources (green: `+totalIncome`)
 - Buying resources (red: `-totalCost`)
 - Sending to another room (red: `sentTo : resourceCount resourceType`)
 - Receiving from another room (green: `sentFrom : resourceCount resourceType`)
 - Sending to another player (red: `sentToRoom : resourceCount resourceType`)
 - Receiving from another player (green: `sentFromRoom : resourceCount resourceType`)
